services:
  app:
    container_name: app
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
      - "5173:5173"  # Vite
    volumes:
      - ./project:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blogs
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
